name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        # NOTE: For information about Elixir and Erlang/OTP versions:
        # https://hexdocs.pm/elixir/compatibility-and-deprecations.html
        include:
          - elixir: "1.4.5"
            otp: "20.3"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
      - run: mix deps.get
      - run: mix test
