name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.12.3, 1.11.4, 1.10.4, 1.9.4, 1.8.2, 1.7.4, 1.6.6, 1.5.3, 1.4.5]
    container: elixir:${{ matrix.elixir }}
    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install Hex
      run: mix local.hex --force
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
