name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test
    strategy:
      fail-fast: false
      matrix:
        elixir:
          [
            "1.4.5",
            "1.5.3",
            "1.6.6",
            "1.7.4",
            "1.8.2",
            "1.9.4",
            "1.10.4",
            "1.11.4",
            "1.12.3",
            "1.13",
            "1.14",
          ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
