name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  MIX_ENV: test

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.12.3, 1.11.4, 1.10.4, 1.9.4, 1.8.2, 1.7.4, 1.6.6, 1.5.3, 1.4.5, 1.3.4, 1.2.6]
        otp: [24.1.6, 23.3.4, 22.3.4, 21.3.8, 20.3.8, 19.3.6, 18.3.4]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: ${{ matrix.elixir }} # Define the elixir version [required]
        otp-version: ${{ matrix.otp }} # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
